#pragma config(Sensor, dgtl1,  startbutton,    sensorTouch)
#pragma config(Motor,  port1,           leftmotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           clawmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armmotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Clawbots
Team Members:  Travis Weir, Clay Hoover
Date:					5/4/17
Section:


Task Description: Make our robot go through the maze without hitting a "wall" and also get a water bottle


Pseudocode:
*/
void driveforward(int howlongtogoforward) //Define the driveforward function and an argument for how many seconds to go forward
{
	startMotor(leftmotor, -100);						//Start the left motor
	startMotor(rightmotor, -100);						//Start the right motor
	wait(howlongtogoforward * .9);					//Wait however many seconds were passed from when the function was called (.85 for more accuracy)
	stopMotor(leftmotor);										//Stop the left motor
	stopMotor(rightmotor);									//Start the right motor
}
void drivebackward(int howlongtodrive)		//Define the drivebackward function and an argument for how long to go backwards
{
	startMotor(leftmotor, 100);						//Start the left motor
	startMotor(rightmotor, 100);						//Start the right motor
	wait(howlongtodrive);										//Wait for how long the function was defined to go
	stopMotor(leftmotor);										//Stop the left motor
	stopMotor(rightmotor);									//Stop the right motor
}
void pivotright90()												//Define the pivot right 90 degrees function
{
	startMotor(leftmotor, -100);						//Start the left motor
	startMotor(rightmotor, 100);						//Start the right motor
	wait(.5375);															//Wait for .525 seconds for the turn to execute
	stopMotor(leftmotor);										//Stop the left motor
	stopMotor(rightmotor);									//Stop the right motor
}
void pivotleft90()												//Define the pivot left 90 degrees function
{
	startMotor(leftmotor, 100);							//Start the left motor
	startMotor(rightmotor, -100);						//Start the right motor
	wait(.5175);														//Wait an amount of 5.175 seconds for the turn to complete
	stopMotor(leftmotor);										//Stop the left motor
	stopMotor(rightmotor);									//Stop the right motor
}
void comingbackrightturn()
{
	startMotor(leftmotor, -100);						//Start the left motor
	startMotor(rightmotor, 100);						//Start the right motor
	wait(.6);																//Wait for .6 seconds for the turn to execute
	stopMotor(leftmotor);										//Stop the left motor
	stopMotor(rightmotor);									//Stop the right motor
}
void mazereverse()												//Define the mazereverse function, which will make the robot do the maze from finish to start.
{
	drivebackward(1);												//Drive backward for 1 second
	comingbackrightturn();									//Pivot right 90 degrees
	driveforward(1);												//Drive forward for 1 second
	pivotleft90();													//Pivot left 90 degrees
	driveforward(2);												//Drive forward for 2 seconds
	pivotright90();													//Pivot right 90 degrees
	driveforward(1);												//Drive backward into the start area
}
void maze()																//Define the maze task, which will make the robot run the maze.
{
	untilBump(startbutton);									//Wait for the start button
	driveforward(1);
	pivotleft90();
	driveforward(2);
	pivotright90();
	driveforward(1);
	pivotright90();
	driveforward(1);
}
void waterbottle()
{
	startMotor(clawmotor, 100);
	wait(0.25);
	stopMotor(clawmotor);
	maze();																	//Call the maze function
	wait(0.5);															//Wait 0.5 seconds for the system to line up properly
	startMotor(clawmotor, -100);						//Start the claw motor
	wait(0.25);															//Give it a bit of time to close
	stopMotor(clawmotor);										//Stop the claw motor
	startMotor(armmotor, -127);							//Start the arm motor
	wait(0.5);															//Give it some time to lift the bottle
	stopMotor(armmotor);										//Stop the arm motor
	mazereverse();													//Do the maze in reverse
}
void victorydance()												//Define the victorydance subroutine
{
	untilBump(startbutton);									//Wait for the start button to be pressed
	startMotor(leftmotor, 127);							//Start the motors in opposite directions
	startMotor(rightmotor, -127);						//""
	untilBump(startbutton);									//Wait for the button to turn it off
	stopMotor(leftmotor);										//Stop the left motor
	stopMotor(rightmotor);									//Stop the right motor
}
task main();
{
	while (true)														//Make an infinite loop
	{
		maze();																//Call the maze task
		mazereverse();												//Back up through the maze
		waterbottle();												//Call the water bottle task
		victorydance();												//Call the victory dance task
	}
}
