#pragma config(Sensor, dgtl1,  startbutton,    sensorTouch)
#pragma config(Motor,  port1,           runmotor,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)												//Make an infinite loop
	{
		untilBump(startbutton);						//Wait for the start button
		startMotor(runmotor, -127);				//Start the motor at full power
		wait(.25);												//Wait 1/4 of a second
		stopMotor(runmotor);							//Stop the motor
	}
}
