#pragma config(Sensor, dgtl1,  green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl2, yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  button,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
turnLEDOn(red);
turnLEDOn(yellow);
turnLEDOn(green);
wait(5);
turnLEDOff(red);
turnLEDOff(yellow);
turnLEDOff(green);
wait(5);

}
