#pragma config(Sensor, dgtl1,  Starter,        sensorTouch)
#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		while(SensorValue[Starter] == 1)
		{
			startMotor(motor1, 127);
			startMotor(motor2, -127);
		}
	stopMotor(motor1);
	stopMotor(motor2);
	}
}
