#pragma config(Sensor, in1,    linefollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  limitswitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpswitch,     sensorTouch)
#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightmotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftmotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: testbed
Team Members: Travis Weir
Date: 2.28.2017
Section:


Task Description: Test our programming


Pseudocode:

*/


                                    //Program begins, insert code within curly braces
/*	while (true){
		int speed = SensorValue[potentiometer];
		startMotor(leftmotor, speed);						//Start left motor
		untilBump(bumpswitch, 500);						//Wait until bump switch
		stopMotor(leftmotor);									//Stop left motor
		startMotor(rightmotor, -127); 				//Start right motor
		untilBump(bumpswitch, 500);							//Wait for bump switch
		stopMotor(rightmotor);								//Turn off left motor
*/

task main()
{
	while (true)
		if(SensorValue[bumpswitch] == 1)	//If the bumpswitch is pressed
			{
				turnLEDOn(led);					//Turn on LED
			}
			else											//Otherwise
			{
			turnLEDOff(led);					//Turn off LED
	}
}
