#pragma config(Sensor, in1,    linefollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  limitswitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpswitch,     sensorTouch)
#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightmotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftmotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: testbed
Team Members: Travis Weir
Date: 2.28.2017
Section:


Task Description: Test our programming


Pseudocode:

*/

task main()
{
	bool reverse = false;
	while (true) {
		while (SensorValue[bumpswitch] == 0){							//Loop while the bump switch isn't pressed
			int speedvalue = SensorValue[potentiometer];	//Get the value of the potentiometer sensor and store in speedvalue var
			int speed = speedvalue / 35;					//Divide potentiometer input by 35 to make it less sensitive
			if (SensorValue[limitswitch] == 1)
			{
				if (reverse == false)
				{
					bool reverse = true;
				}
			}
			if (SensorValue[limitswitch] == 0) {
				if (reverse == true){
					bool reverse = false;
				}
			}
			if (reverse == false)
			{
				speed = speed * -1;
			}
	startMotor(leftmotor, speed);						//Start left motor at speed from calculation
	startMotor(rightmotor, speed);					//Start right motor at speed
	untilBump(bumpswitch);
		}
	}
}
