#pragma config(Sensor, dgtl1,  green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  button,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: City Programmer
Team Members: Travis Weir, Chris Lee, Trevor Lewis
Date: 3/20/2017
Section: "Terry Traffic Tamer"


Task Description: Design a traffic light that can be switched to red to allow for passage of an ambulance at the push of a button


Pseudocode:

*/

void redlight()     	//Create a subroutine to run the redlight
{
	turnLEDOn(red);			//Turn on the red LED
	wait(5);						//Wait 5 seconds
	turnLEDOff(red);		//Turn off red LED
}
void yellowlight()		//Create a subroutine to run the yellow light
{
	turnLEDOn(yellow);	//Turn on the yellow light
	wait(1);						//Wait 1 second
	turnLEDOff(yellow); //Turn off the yellow light
}
void greenlight()			//Create a subroutine to run the greenlight sequence
{
	turnLEDOn(green); 	//Turn on green LED
	wait(5);						//Wait 5 seconds
	turnLEDOff(green); 	//Turn off green LED
}
task ambulance()			//Create a task that runs in the background to check for the button
{
	while (true)				//Create an infinite loop
	{
		if (SensorValue[button] == 1) //If the button is pressed
		{
			turnLEDOff(red);		//Turn off the red LED
			turnLEDOff(green);	//Turn off the green LED
			turnLEDOn(yellow);	//Turn on the yellow LED
			wait(1);						//Wait 1 second
			turnLEDOff(yellow);	//Turn off the yellow LED
			while (SensorValue[button] == 1) //While the button is pressed
			{
				turnLEDOn(red);			//Turn on the red LED
				turnLEDOff(yellow); //Turn off the yellow LED
				turnLEDOff(green);  //Turn off the green LED
			}
			turnLEDOff(red);			//After the button is no longer pressed, turn off the red LED
		}
	}
}
task main()
{
	startTask(ambulance);			//Start the previously defined ambulance task
	while (true)							//Create an infinite loop
	{
		if (SensorValue[button] == 0) //If the button is pressed,
		{
			greenlight();						//Run the green light subroutine
			yellowlight();					//Run the yellow light subroutine
			redlight();							//Run the red light subroutine
		}
	}
}
