#pragma config(Sensor, in1,    linefollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  limitswitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpswitch,     sensorTouch)
#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightmotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftmotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: testbed
Team Members: Travis Weir
Date: 2.28.2017
Section:


Task Description: Test our programming


Pseudocode:

*/

task main()
/*
{
	while (true)
	{
		int speedvalue = SensorValue[potentiometer];
		int speed = speedvalue / 30;
		if (SensorValue[limitswitch] == 1)
		{
			int speed = speed * -1;
		}
		else
		{
			speed = speed;
		}
		if (SensorValue[bumpswitch] == 1)
		{
			int speed = 0;
		}
		else
		{
			speed = speed;
		}
		startMotor(leftmotor, speed);
		startMotor(rightmotor, speed);
	}
}
*/
{
	startMotor(leftmotor, -127);
	startMotor(rightmotor, -127);
	untilBump(bumpswitch);
	startMotor(leftmotor, 127);
	startMotor(rightmotor, 127);
	untilBump(bumpswitch);
	stopMotor(leftmotor);
	stopMotor(rightmotor);
	turnLEDOn(led);
}
